import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';

import '../../data/local/language_store.dart';
import '../../firebase_options.dart';
import 'push_notification_handler.dart';

/// Firebase Cloud Messaging glue for [PushNotificationHandler].
///
/// Firebase project "Kindra App" (`kindra-app-ve`), apps
/// `com.homecare.android` / `com.homecare.ios`. The config
/// ([DefaultFirebaseOptions], `google-services.json`,
/// `GoogleService-Info.plist`) is generated by `flutterfire configure`.
/// If Firebase fails to start, push stays off and the app still works.
///
/// * [initialize] once at launch.
/// * [onSignedIn] after sign-in: asks permission, registers the token
///   (`POST /devices`) and opens the screen of a tapped notification.
/// * [onSignedOut] stops listening; the device itself is unregistered by
///   [PushNotificationHandler.onSignOut] in `AuthCubit.logout`.
class FirebasePushService {
  FirebasePushService({required this._handler, required this._languageStore});

  final PushNotificationHandler _handler;
  final LanguageStore _languageStore;

  bool _available = false;
  bool _signedIn = false;
  final _subscriptions = <StreamSubscription<Object?>>[];

  /// Tap that arrived before sign-in finished (cold start from a notification).
  Map<String, dynamic>? _pendingTap;

  /// Shown while the app is open; the tab shell listens to show a toast.
  final ValueNotifier<RemoteNotification?> foregroundNotification = ValueNotifier(null);

  bool get isAvailable => _available;

  Future<void> initialize() async {
    try {
      await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
      _available = true;
    } catch (error) {
      debugPrint('Push off: Firebase failed to start ($error)');
      return;
    }

    final messaging = FirebaseMessaging.instance;
    // iOS: show banners while the app is open too.
    await messaging.setForegroundNotificationPresentationOptions(alert: true, badge: true, sound: true);

    _subscriptions.add(FirebaseMessaging.onMessageOpenedApp.listen((m) => _onTap(m.data)));
    _subscriptions.add(FirebaseMessaging.onMessage.listen((m) {
      if (m.notification != null) foregroundNotification.value = m.notification;
    }));
    _subscriptions.add(messaging.onTokenRefresh.listen((token) {
      _logToken(token, 'refreshed');
      unawaited(_sendToken(token));
    }));
    _languageStore.language.addListener(_onLanguageChanged);

    final initial = await messaging.getInitialMessage();
    if (initial != null) _pendingTap = initial.data;

    // Android has a token right away; iOS only after permission (see onSignedIn).
    if (kDebugMode) {
      try {
        _logToken(await messaging.getToken(), 'app start');
      } catch (error) {
        debugPrint('FCM token not available yet: $error');
      }
    }
  }

  /// Debug builds only: prints the token for Firebase Console → Messaging →
  /// "Send test message".
  static void _logToken(String? token, String when) {
    if (!kDebugMode) return;
    debugPrint('════════ FCM TOKEN ($when) ════════');
    debugPrint(token ?? '(none)');
    debugPrint('═══════════════════════════════════');
  }

  Future<void> onSignedIn() async {
    _signedIn = true;
    if (!_available) return;
    try {
      final settings = await FirebaseMessaging.instance.requestPermission();
      if (settings.authorizationStatus == AuthorizationStatus.authorized ||
          settings.authorizationStatus == AuthorizationStatus.provisional) {
        final token = await FirebaseMessaging.instance.getToken();
        _logToken(token, 'signed in');
        await _sendToken(token);
      } else {
        debugPrint('FCM: notification permission ${settings.authorizationStatus.name}');
      }
    } catch (error) {
      debugPrint('Push token registration failed: $error');
    }
    final pending = _pendingTap;
    _pendingTap = null;
    if (pending != null) await _onTap(pending);
  }

  void onSignedOut() => _signedIn = false;

  /// This phone's FCM token for `POST /login` / `POST /logout`, or `null`
  /// when push is off or no token is available yet (iOS before permission).
  /// Never waits long: sign-in and sign-out must not hang on Firebase.
  Future<String?> currentToken() async {
    if (!_available) return null;
    try {
      final token = await FirebaseMessaging.instance
          .getToken()
          .timeout(const Duration(seconds: 3));
      return token == null || token.isEmpty ? null : token;
    } catch (_) {
      return null;
    }
  }

  Future<void> _sendToken(String? token) async {
    if (!_signedIn || token == null) return;
    try {
      await _handler.onToken(token);
    } catch (error) {
      debugPrint('Push token registration failed: $error');
    }
  }

  /// The server localizes pushes, so the token is re-sent with the new language.
  void _onLanguageChanged() {
    if (!_signedIn || !_available) return;
    unawaited(FirebaseMessaging.instance.getToken().then(_sendToken).catchError((Object _) {}));
  }

  Future<void> _onTap(Map<String, dynamic> data) async {
    if (!_signedIn) {
      _pendingTap = data;
      return;
    }
    await _handler.onNotificationTap(data);
  }
}
